server:
  port: 8080

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j.retry:
  instances:
    facade:
      waitDuration: 2s
      maxAttempts: 4
#      enableExponentialBackoff: true
#      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException

resilience4j.circuitbreaker:
  instances:
    facade:
      minimumNumberOfCalls: 8
      waitDurationInOpenState: 60s
      permittedNumberOfCallsInHalfOpenState: 1 # one successful request to fully close the circuit
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
      automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){magenta} %clr([%15.15t]){cyan} %clr(:){red} %clr(%m){yellow}%n"
